namespace Match3
{
    public enum TileID : short
    {
        None = 0,
        RedFlower = 1,
        YellowFlower = 2,
        PurpleFlower = 3,
        BlueFlower = 4,
        WhiteFlower = 5,
        RedCandle = 6,
        YellowCandle = 7,
        GreenCandle = 8,
        BlueCandle = 9,
        WhiteCandle = 10,
        RedRibbon = 11,
        YellowRibbon = 12,
        GreenRibbon = 13,
        BlueRibbon = 14,
        PurpleRibbon = 15,
        MagnifyingGlass = 16,
        BlueFeather = 17,
        GreenFeather = 18,
        PurpleFeather = 19,
        RedFeather = 20,
        WhiteFeather = 21,
        YellowFeather = 22,
        BlueMushroom = 23,
        GreenMushroom = 24,
        PurpleMushroom = 25,
        RedMushroom = 26,
        YellowMushroom = 27,
        GreenBut = 28,
        PurpleBut = 29,
        RedBut = 30,
        WhiteBut = 31,
        YellowBut = 32,
        RedBug = 33,
        YellowBug = 34,
        Rock = 35,

        Bell = 36,
        BlueBallon = 37,
        BlueWool = 38,
        BrownMushRoom = 39,
        BrownRock = 40,
        Charcoal = 41,
        Flyfire = 42,
        GreenBallon = 43,
        GreenWool = 44,
        Lantern = 45,
        Onion = 46,
        PurpleBallon = 47,
        PurpleWool = 48,
        RedBallon = 49,
        RedWool = 50,
        Shushi_1 = 51,
        Shushi_2 = 52,
        Shushi_3 = 53,
        Shushi_4 = 54,
        Shushi_5 = 55,
        Shushi_6 = 56,
        Shushi_7 = 57,
        Shushi_8 = 58,
        Shushi_9 = 59,
        MeetBall =60,
        Tape = 61,
        WhiteBallon = 62,
        WhiteWool = 63,
        WoodLog = 64,
        YellowBallon = 65,
        YellowWool = 66,
        Cheese =67,
        Fish =68,
        Corn = 69,
        Duck = 70,
        Fire =71,
        Raw_Meat =72,
        Red_Chillie =73,
        Tomato = 74,
        Soap = 75,
        Cookie = 76,
        Egg =77,
        Green_Vegetable =78,



        // Speical Tile
        BlastBomb = 5000,
    }

    public enum SpecialTileID 
    {
        None = 0,
        ColumnBomb = 1,
        RowBomb = 2,
        BlastBomb = 3,
        ColorBurst = 4,
    }
}
